name: step_sync
description: >
  This package was created by [Ali Eren Tabak](https://github.com/AliEren04).
  A package that counts steps and allows daily reset using the reset method.

version: 3.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

repository: https://github.com/AliEren04/step_sync
homepage: https://github.com/AliEren04/step_sync

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^3.0.3
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.3.1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
